---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

data<-read.csv("activity.csv")
data$date<-as.Date(data$date)


##Histogram without NA values
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 

hist(sum_steps$x, 
      breaks=seq(from=0, to=25000, by=2500),
      col="red", 
      xlab="Total number of steps", 
      ylim=c(0, 20), 
      main="Histogram of the total number of steps taken each day\n(NA removed)")

##Mean and median number of steps taken each day
mean(sum_steps$x)
median(sum_steps$x)

##Time series plot of the average number of steps taken
avg_steps<-aggregate(data$steps,by=list(data$interval),FUN=mean,na.rm=TRUE)

colnames(avg_steps)<-c("interval","steps")

library(ggplot2)
ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()


##The 5-minute interval that, on average, contains the maximum number of steps
avg_steps[avg_steps$steps==max(avg_steps$steps),1]


##Here is code to describe and show a strategy for imputing missing data
sum(is.na(data$steps))

##Replace NA values with the mean of the steps
data$steps[is.na(data$steps)]<-mean(data$steps,na.rm=TRUE)

head(data)

##Histogram of total number of steps taken on each day is shown below:
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 

hist(sum_steps$x, 
      breaks=seq(from=0, to=25000, by=2500),
      col="yellow", 
      xlab="Total number of steps", 
      ylim=c(0, 30), 
      main="Total number of steps taken each day\n(NA replaced by mean)")

##Mean and median number of steps taken each day after replacing NA values with mean
mean(sum_steps$x)
median(sum_steps$x)

##Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
data$days=tolower(weekdays(data$date))
data$day_type<-ifelse(data$days=="saturday"|data$days=="sunday","weekend","weekday")
avg_steps<-aggregate(data$steps,by=list(data$interval,data$day_type),FUN=mean,na.rm=TRUE)

colnames(avg_steps)<-c("interval","day_type","steps")
ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()+facet_wrap(~avg_steps$day_type)
library(knitr)
knit("PA1_template.Rmd")

